title: Proxeuse Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.proxeuse.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: Jan 2 — 15:04 UTC
  down: "#e60000"
  systems:
    - name: Plesk - Falkenstein (DE) - fsn1_dc14_cloud
      category: Servers
    - name: Nextcloud Storage Backend - Falkenstein (DE) - FSN1-BX155 Online
      category: Servers
    - name: Proxeuse - Live Chat
      category: Services
    - name: Proxeuse - Customer Portal
      category: Services
    - name: Proxeuse - Documentation
      category: Services
    - name: Proxeuse - Downloads Portal
      category: Services
    - name: Proxeuse - Portainer
      category: Services
    - name: Proxeuse - Pterodactyl
      category: Services
    - name: API - Payments - Stripe
      category: Vendors
    - name: API - Payments - PayPal
      category: Vendors
    - name: API - Cloud Servers - Hetzner
      category: Vendors
    - name: API - Domain Registration - OpenProvider
      category: Vendors
    - name: DNS1 - Falkenstein (DE) - fsn1_dc14_cloud
      category: DNS
    - name: DNS2 - Helsinki (FI) - hel1_dc2_cloud
      category: DNS
    - name: DNS3 - Dusseldorf (DE) - dus1_hetz_dns
      category: DNS
    - name: DNS4 - Gunzenhausen (DE) - gun1_hetz_dns
      category: DNS
    - name: DNS5 - Frankfurt am Main (DE) - fra_hetz_dns
      category: DNS
  dateFormat: Mon, 02 Jan 2006 15:04:05 UTC
  brand: "#24c178"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo-wit.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: Uptime Statistics
      link: https://statping.proxeuse.com
    - name: Example
      link: pages/example-page
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Servers
      closed: false
      untitled: false
    - name: Services
      closed: false
    - name: Vendors
      closed: true
    - name: DNS
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
